### ISSUE TITLE
not compatible with the old extension

### ISSUE THREAD

**Issue by arneschween** [simu/passwordhasherplus#11]
the old extension had a restriction based generation that even generated special characters, when not required to do so.

Try site tag twitter with master key/passphrase 123456, 8 characters to generate. The old extension generates scxqJ/Lx with all requirements unchecked, the new one has to be switched to alphanumeric+special (in compatibily mode of course) to generate the same password.

Then try the master key/passphrase aaaaaa, old generates: q6oCYnFI .. and new hast to be switched to alphanumeric to generate the same password. 

So there is no setting to generate passwords identical to the old extension reliably.

**Comment by simu** [comment]
Thanks for the report.

Currently, the new extension doesn't offer individual controls over the flags present in the old extension but rather computes a set of flags given the choice of "Alphanumeric+Special", "Alphanumeric", and "Numeric", which map to the old check boxes as follows:

Option | At least one digit | At least one punctuation character | Both upper- and lower-case letters | No special characters | Digits only
--------|-------------------|------------------------------------|-------------------------------------|--------|-----------
Alphanumeric+Special | ✔️  | ✔️  | ✔️  | ❌  | ❌ 
Alphanumeric | ✔️  | ❌  | ✔️  | ✔️  | ❌  | ❌  
Numeric | ✔️  | ❌  | ✔️  | ❌  | ✔️ 

The back-end understands all the individual flags and provides identical hash words to the ones you specify if those individual flags are set correctly. Here's a link to the implementation: https://github.com/simu/passwordhasherplus/blob/d1d776260d58df598abb6e9cbde9109af538a661/lib/passhashcommon.js#L48-L90

However the original author of this extension chose to implement the three options listed above rather than exposing the individual controls:
https://github.com/simu/passwordhasherplus/blob/d1d776260d58df598abb6e9cbde9109af538a661/common.js#L109-L118

As you can see your combination of check boxes unfortunately doesn't map to any of the higher level options which are available in the extension at the moment.

For the second code snippet, the variable `config.policy.strength` corresponds to the options in the extension as shown below.

Option | Strength
--------|---------
Alphanumeric+Special | 2
Alphanumeric | 1
Numeric | 0

I will look into providing more fine-grained control over the generation -- probably only in compatibility mode -- if I find some more time to work on this.

**Comment by phreaknerd** [comment]
Compatible with the old one? https://addons.mozilla.org/en-US/firefox/addon/password-hasher-ng/
Maybe you can snatch some code there: https://github.com/phreaknerd/passhash-ng

Feedback very much appreciated.

**Comment by simu** [comment]
Looks like your addon is doing what I'm planning to do with regard to compatibility / putting the master password field in the popup (cf. #3).
I'll probably end up grabbing some of the tedious bits (e.g. adding new UI elements) from you :)

**Comment by simu** [comment]
If you were using custom settings for hash generation, check out release 2.4.0a11 on AMO which exposes the old settings if you choose password strength "Custom" and should generate hash words which are compatible with the old extension for all combinations.

Note that "Digits only" is already available in the strength option "Numeric" and thus does not appear as a possible restriction in "Custom".

**Comment by simu** [comment]
The new stable version on AMO, 2.4.0, has the "Custom" strength option.
