### ISSUE TITLE
Making hash-mode the default

### ISSUE THREAD

**Issue by mboehmhh** [simu/passwordhasherplus#15]
I wonder if there should be an option that makes hashing the default. By now its up to the user to switch from normal passwords to hashing it should be vice versa in my opinion. This will also reduce or eliminate the problem of sending the master key across the network accidently.

**Comment by simu** [comment]
I'm working on moving towards a model where the user never types anything in the context of the website, see branches [dialog_in_page_action](/simu/passwordhasherplus/tree/dialog_in_page_action) and [no-jquery](/simu/passwordhasherplus/tree/no-jquery).

This is currently not merged because Firefox has trouble moving focus between the website and the addon's popup correctly which means extra mouse movements and clicks for users that are accustomed to just using the keyboard shortcut to open the hashing dialog and then pressing enter twice to log in. According to the bug report (https://bugzilla.mozilla.org/show_bug.cgi?id=1324255) this should be fixed in Firefox 60.0 but I haven't had time to test yet.

**Comment by simu** [comment]
With the UI and workflow changes in #20 which are released in [v2.5.0](https://github.com/simu/passwordhasherplus/releases/tag/v2.5.0), the issue of sending the master key on the network is completely eliminated.
