### ISSUE TITLE
'Password Hasher Plus - Options' do not survive Firefox history deletion

### ISSUE THREAD

**Issue by ghost** [simu/passwordhasherplus#4]
Hello simu,

the options of Password Hasher Plus do not survive while you delete complete Firefoxs history. 
I did not test which certian part of Firefoxs history you have to delete exactly to also delete the options of Password Hasher Plus. But settings of other extensions like uBlock Origin survive the deletion.

Tested on Firefox 56.0.2. (32-Bit) Windows,
Password Hasher Plus - Password Generator 2.3.10.

Best regards

**Comment by simu** [comment]
Currently, the extension is using local storage for the options.

This has the obvious downside that the options will disappear if you delete all history.

The correct way to do this is to use the WebExtensions storage API, which will not get cleared if the user clears the history.

**Comment by simu** [comment]
I've had a go at writing a new options storage backend which uses the webextensions storage API. You can test it by going to the addon's [beta version page](https://addons.mozilla.org/en-US/firefox/addon/password-hasher-plus/versions/beta) and installing version 2.4.0a2.

Your current settings should be converted and stored in the storage API storage area.

I currently make no guarantees, so it's probably best if you make a backup of your current settings before trying it out.

The changes are available on branch webextensions_storage, the current alpha version is tagged as [v2.4.0a2](https://github.com/simu/passwordhasherplus/tree/v2.4.0a2)

**Comment by elektroschrott** [comment]
Same here, even with only restarting FF the options are completey lost (FF 56 32bit and FF 57).
With the beta 2.4.0a2 this problem seems to be fixed, but: the shown hash changes when clicking with the mouse to anywhere ...:
I typed the masterPW, changed it by hotkey to the hash, then I masked the hash by hotkey and the hash is correct. But when I click to anywhere on the site, the hash chances to total different hash with the same length. WTF?? I tried this with different sites, same bug.

**Comment by simu** [comment]
@elektroschrott Have you tried one of the newer beta versions? The latest beta is 2.4.0a12. The other issue sounds like an issue I've been trying to track down, one of the "features" of the extension is that it remembers fields which you selected to be hashed and tries to be helpful by rehashing the contents when it thinks it's necessary. However this does not always work right. I'm looking to move away from the design of entering the password directly in the password field, see #3, as that method of entering the master password has multiple issues, not the least of which is malicious pages being able to steal the master password.

The bug in this issue -- settings not surviving deleting history -- should be fixed by the use of the WebExtensions storage API in [v2.4.0](https://github.com/simu/passwordhasherplus/tree/v2.4.0), which is available on AMO now.
